@echo off
echo Reiniciando o servidor Next.js...
echo Parando os processos do Next.js...
taskkill /f /im node.exe >nul 2>&1
echo Limpando cache...
if exist .next rd /s /q .next
echo Instalando dependências...
call npm install
echo Iniciando o servidor...
call npm run dev
